### ISSUE TITLE
Important database information is exposed

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#160]
Hey Mike (and Keith),

Not sure who I should report this too, but it looks like the CS103 database credentials are exposed...

(1) 4:09pm
sredmond@myth6:~/cs103> cd /afs/.ir.stanford.edu/class/cs103/db_config/

(2) 4:09pm
sredmond@myth6:db_config> ls
prodconfig.yaml

(3) 4:09pm
sredmond@myth6:db_config> cat prodconfig.yaml
# StanfordApp YAML configuration file

database:
  name: c_cs103_db
  username: <the_username>
  password: <the_password>
  use encryption: yes

settings:
  undo magic quotes: yes

Also, everything in /afs/.ir.stanford.edu/class/cs103/old-automata-tools/cgi-bin/ is readable (and maybe writable? I haven't tried) - including the CS103DB.php script, which connects to the StanfordDatabase that holds the CS103 information and could presumably be manipulated for nefarious purposes.

This seems like not a big deal to fix - just a few chmods - and it's hopefully not a serious vulnerability, but nevertheless I thought I'd let you know to prevent any malicious activity that might happen.

Cheers,
Sam

**Comment by bakkot** [comment]
Think I fixed this shortly after it was reported. Will verify when I get home.

**Comment by bakkot** [comment]
Yup, has been fixed since 30 minutes after it was reported, not to worry. For reference, on farmshare, `fs la [directory containing sensitive information]` should give a list including `class-cs103-1156.cgi` at at least `rl` (so the scripts can access stuff) but not including `system:anyuser` (so users can't). Ensure you yourself have appropriate permissions first, of course.
